sudo: required
services:
  - docker

before_install:
  - docker build -t rithvik21/docker-react -f Dockerfile.dev .  

script:
  - docker run -e CI=true rithvik21/docker-react npm run test -- --coverage